import { FishSpecies } from '../ai/types';

export const SPECIES_DATABASE: Record<string, FishSpecies> = {
  rohu: {
    id: 'rohu',
    commonName: 'Rohu',
    scientificName: 'Labeo rohita',
    family: 'Cyprinidae',
    diet: 'Herbivorous / Column feeder (Phytoplankton & algae)',
    nativeRegion: 'South Asian river basins (Ganges, Indus, Brahmaputra) & Aquaculture',
    commercialValue: 'High commercial demand; premier Indian major carp',
    culinaryNotes: 'Rich in Omega-3 fatty acids, mild sweet flavor, tender flaky meat. Ideal for Shorshe Bata (mustard curry) or crisp pan-frying.',
    optimalTempC: '0°C to 4°C (on crushed ice)',
    shelfLifeDays: 4,
    aCoeff: 0.0125,
    bCoeff: 3.02,
    defaultLengthCm: 38,
    sampleImageUri: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
  },
  catla: {
    id: 'catla',
    commonName: 'Catla',
    scientificName: 'Catla catla',
    family: 'Cyprinidae',
    diet: 'Surface feeder (Zooplankton & micro-crustaceans)',
    nativeRegion: 'Freshwater rivers, lakes, and reservoirs across South Asia',
    commercialValue: 'Premium table fish; highly prized for head (Muri) and belly cuts (Peti)',
    culinaryNotes: 'Firm white meat with large distinct flakes. Excellent for rich slow-simmered curries and fish head dal.',
    optimalTempC: '0°C to 4°C',
    shelfLifeDays: 3,
    aCoeff: 0.0142,
    bCoeff: 2.98,
    defaultLengthCm: 46,
    sampleImageUri: 'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?auto=format&fit=crop&w=800&q=80',
  },
  tilapia: {
    id: 'tilapia',
    commonName: 'Tilapia',
    scientificName: 'Oreochromis niloticus',
    family: 'Cichlidae',
    diet: 'Omnivorous (Aquatic plants, detritus, plankton)',
    nativeRegion: 'Global aquaculture / Tropical freshwater and brackish bodies',
    commercialValue: 'High-volume commercial market, everyday budget staple',
    culinaryNotes: 'Lean, delicate flavor with slightly sweet undertones. Best grilled with masala, shallow fried, or steamed with ginger-garlic.',
    optimalTempC: '0°C to 3°C',
    shelfLifeDays: 5,
    aCoeff: 0.0189,
    bCoeff: 2.89,
    defaultLengthCm: 28,
    sampleImageUri: 'https://images.unsplash.com/photo-1534043464124-3be32fe000c9?auto=format&fit=crop&w=800&q=80',
  },
  hilsa: {
    id: 'hilsa',
    commonName: 'Hilsa',
    scientificName: 'Tenualosa ilisha',
    family: 'Clupeidae',
    diet: 'Plankton feeder / Anadromous marine & riverine',
    nativeRegion: 'Bay of Bengal, Arabian Sea, Padma, Meghna, and Hooghly estuaries',
    commercialValue: 'Highest value cultural delicacy in South Asian seafood',
    culinaryNotes: 'Exceptionally tender, oily meat with distinct aromatic oils. Renowned for Ilish Bhapa (steamed mustard), Shorshe Ilish, and Paturi.',
    optimalTempC: '-1°C to 2°C (rapid chilling recommended)',
    shelfLifeDays: 3,
    aCoeff: 0.0098,
    bCoeff: 3.12,
    defaultLengthCm: 35,
    sampleImageUri: 'https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80',
  },
  mrigal: {
    id: 'mrigal',
    commonName: 'Mrigal',
    scientificName: 'Cirrhinus cirrhosus',
    family: 'Cyprinidae',
    diet: 'Bottom feeder / Detritivore (Decaying organic matter & benthic fauna)',
    nativeRegion: 'River systems across India, Bangladesh, and Pakistan',
    commercialValue: 'Major Indian carp (essential member of Composite Fish Culture)',
    culinaryNotes: 'Leaner than Rohu with fine texture and subtle taste. Popular for homestyle spicy curries and pan-frying with turmeric and chili.',
    optimalTempC: '0°C to 4°C',
    shelfLifeDays: 4,
    aCoeff: 0.0118,
    bCoeff: 3.05,
    defaultLengthCm: 34,
    sampleImageUri: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&w=800&q=80',
  },
  indian_mackerel: {
    id: 'indian_mackerel',
    commonName: 'Indian Mackerel / Bangda',
    scientificName: 'Rastrelliger kanagurta',
    family: 'Scombridae',
    diet: 'Pelagic plankton feeder',
    nativeRegion: 'Indo-West Pacific coastal waters (Konkan, Malabar, Coromandel coasts)',
    commercialValue: 'High-volume everyday catch; essential coastal staple in India',
    culinaryNotes: 'Rich oily fish with bold savory flavor. Iconic in Bangda Fry (Rava crusted), Goan Bangddeche Kodi (coconut curry), and Meen Pollichathu.',
    optimalTempC: '0°C to 2°C',
    shelfLifeDays: 3,
    aCoeff: 0.0105,
    bCoeff: 3.08,
    defaultLengthCm: 25,
    sampleImageUri: 'https://images.unsplash.com/photo-1524704654690-b56c05c78a00?auto=format&fit=crop&w=800&q=80',
  },
  pomfret: {
    id: 'pomfret',
    commonName: 'Pomfret / Paplet',
    scientificName: 'Pampus argenteus / Parastromateus niger',
    family: 'Stromateidae / Carangidae',
    diet: 'Pelagic carnivore (Jellyfish, salps, small crustacea)',
    nativeRegion: 'Coastal waters of the Indian Ocean, Arabian Sea & Bay of Bengal',
    commercialValue: 'Top-tier luxury seafood; premium market price across India',
    culinaryNotes: 'Buttery, tender white meat with very few bones (single central spine). Famous for Tandoori Pomfret, Paplet Fry, and Green Masala stuffed pomfret.',
    optimalTempC: '0°C to 2°C',
    shelfLifeDays: 4,
    aCoeff: 0.0210,
    bCoeff: 2.92,
    defaultLengthCm: 27,
    sampleImageUri: 'https://images.unsplash.com/photo-1534043464124-3be32fe000c9?auto=format&fit=crop&w=800&q=80',
  },
};
